### ISSUE TITLE
关于 Ant 中 Fork 选项

### ISSUE THREAD

**Issue by Chris-Ju** [se-2018/se-2018.github.io#4]
![](https://github.com/Chris-Ju/Picture/blob/master/JavacFork.jpg?raw=true)
- 如果不添加 可执行文件的地址，默认值是什么？

**Comment by ZhangZekun** [comment]
javac  ecutable 
Description: Complete path to the javac executable to use in case of fork is yes.Since Ant 1.6 this attribute can also be used to specify the path to the executable when using jikes, jvc, gcj or sj. 
Required: No; **defaults to the compiler of current JDK, ignored if fork is no**.

手册：https://ant.apache.org/manual/Tasks/javac.html
